import { Router, type Request, type Response } from "express";
import { authenticateServiceUser, createUserSession, deleteUserSession, getSessionUser, getServiceUser, getUserAiConfig, updateUserAiModel } from "../lib/adminAuth";
import { getClaudeReply } from "../bot/claude";
import { botState } from "../bot/state";

const router = Router();
const validId = /^[a-z0-9-]{3,48}$/;
const validModel = /^[a-zA-Z0-9._:/-]{2,100}$/;
const esc = (s: string) => s.replace(/[&<>"']/g, c => ({ "&":"&amp;", "<":"&lt;", ">":"&gt;", '"':"&quot;", "'":"&#39;" })[c]!);
function page(title: string, body: string) { return `<!doctype html><html lang="vi"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><style>body{margin:0;font:15px system-ui;background:#08090d;color:#e2e8f0}.wrap{max-width:900px;margin:auto;padding:32px 20px}.card{background:#121520;border:1px solid #282d40;border-radius:14px;padding:22px}input,textarea{box-sizing:border-box;width:100%;padding:12px;border-radius:8px;border:1px solid #3a4058;background:#0b0d14;color:#fff;margin:7px 0 15px}button,a.btn{background:#6366f1;color:#fff;border:0;border-radius:8px;padding:10px 15px;text-decoration:none;font-weight:650;cursor:pointer}.muted{color:#94a3b8}.err{color:#fca5a5}.messages{min-height:260px;max-height:55vh;overflow:auto;margin:16px 0}.msg{padding:12px;margin:9px 0;border-radius:9px;background:#1a1e2c;white-space:pre-wrap}.me{background:#292654}.row{display:flex;gap:10px;justify-content:space-between;align-items:center}form.inline{display:inline}</style><body><main class="wrap">${body}</main></body></html>`; }
function current(req: Request, id: string) { const u = getSessionUser((req as any).cookies?.userSession); return u?.id === id ? u : undefined; }
router.get("/u/:id",(req,res):void=>{const id=req.params.id.toLowerCase(),user=getServiceUser(id);if(!validId.test(id)||!user){res.status(404).send("Khong tim thay trang.");return}if(!current(req,id)){res.send(page("Dang nhap",`<div class="card"><h1>${esc(user.name)}</h1><form method="post" action="/u/${id}/login"><label>Mat khau</label><input type="password" name="password" minlength="8" required autofocus><button>Dang nhap</button></form></div>`));return}const c=getUserAiConfig(user.fbThreadId);res.send(page(user.name,`<div class="row"><div><h1>${esc(user.name)}</h1><p class="muted">Messenger thread: ${esc(user.fbThreadId)}</p></div><form method="post" action="/u/${id}/logout"><button>Dang xuat</button></form></div><div class="card"><div class="row"><h2>Gemini AI</h2><a class="btn" href="/u/${id}/gemini">${c?"Ket noi lai":"Ket noi Gemini"}</a></div>${c?`<p class="muted">Da ket noi. Tu chon model cho tai khoan nay:</p><form method="post" action="/u/${id}/model"><label>Model Gemini</label><input name="model" value="${esc(c.model)}" list="models" required><datalist id="models"><option value="gemini-2.0-flash"><option value="gemini-2.5-flash"><option value="gemini-2.5-pro"></datalist><button>Luu model</button></form>`:`<p class="muted">Ket noi Gemini truoc. Sau do ban tu chon model tai day, khong can admin them AI Account.</p>`}</div><div class="card"><h2>AI Chat</h2><div id="messages" class="messages"></div><form id="chat"><textarea id="prompt" required placeholder="Nhap tin nhan..."></textarea><button>Gui</button></form></div><script>const m=document.querySelector("#messages"),f=document.querySelector("#chat"),p=document.querySelector("#prompt");f.onsubmit=async e=>{e.preventDefault();let v=p.value.trim();if(!v)return;m.innerHTML+="<div class=\"msg me\"></div>";m.lastChild.textContent=v;p.value="";let r=await fetch("/u/${id}/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({prompt:v})}),d=await r.json();m.innerHTML+="<div class=\"msg\"></div>";m.lastChild.textContent=d.reply||d.error||"Loi";m.scrollTop=m.scrollHeight}</script>`))});
router.post("/u/:id/login", (req,res) => { const id=req.params.id.toLowerCase(); const u=authenticateServiceUser(id,String(req.body.password??"")); if(!u)return res.redirect(`/u/${id}?err=1`); res.cookie("userSession",createUserSession(id),{httpOnly:true,sameSite:"lax",secure:req.secure,maxAge:604800000});res.redirect(`/u/${id}`); });
router.post("/u/:id/logout",(req,res)=>{deleteUserSession((req as any).cookies?.userSession);res.clearCookie("userSession");res.redirect(`/u/${req.params.id}`)});
router.get("/u/:id/gemini", (req, res) => { const u=current(req,req.params.id.toLowerCase()); if(!u)return res.redirect(`/u/${req.params.id}`); res.redirect("/connect/gemini"); });
router.post("/u/:id/model", (req, res) => { const id=req.params.id.toLowerCase(), u=current(req,id), model=String(req.body.model ?? "").trim(); if (!u || !validModel.test(model) || !updateUserAiModel(u.fbThreadId,model)) { res.redirect(`/u/${id}?modelErr=1`); return; } res.redirect(`/u/${id}?modelSaved=1`); });
router.post("/u/:id/chat",async(req,res): Promise<void>=>{const u=current(req,req.params.id.toLowerCase());const prompt=String(req.body.prompt??"").trim();if(!u){res.status(401).json({error:"Can dang nhap."});return;}if(!prompt){res.status(400).json({error:"Thieu tin nhan."});return;}try{res.json({reply:await getClaudeReply(u.fbThreadId,prompt,botState.systemPrompt)})}catch{res.status(502).json({error:"AI chua san sang. Hay ket noi Gemini hoac lien he admin."})}});
export default router;
