import React from "react";

type StatTone = "red" | "emerald" | "amber" | "purple" | "blue";
type StatCard = { label: string; value: string; trend: string; direction: "up" | "down"; tone: StatTone; icon: React.ReactNode };
type KeyRow = { key: string; status: "Active" | "Pending" | "Blocked" | "Expired"; source: string; country: string; revenue: string; hwid: string; created: string };

const toneClasses: Record<StatTone, { text: string; border: string; glow: string; bg: string }> = {
  red: { text: "text-[#e94560]", border: "border-[#e94560]/35", glow: "shadow-[0_0_34px_rgba(233,69,96,.18)]", bg: "bg-[#e94560]/10" },
  emerald: { text: "text-emerald-400", border: "border-emerald-400/35", glow: "shadow-[0_0_34px_rgba(52,211,153,.16)]", bg: "bg-emerald-400/10" },
  amber: { text: "text-amber-400", border: "border-amber-400/35", glow: "shadow-[0_0_34px_rgba(251,191,36,.14)]", bg: "bg-amber-400/10" },
  purple: { text: "text-purple-400", border: "border-purple-400/35", glow: "shadow-[0_0_34px_rgba(192,132,252,.16)]", bg: "bg-purple-400/10" },
  blue: { text: "text-sky-400", border: "border-sky-400/35", glow: "shadow-[0_0_34px_rgba(56,189,248,.16)]", bg: "bg-sky-400/10" },
};

const stats: StatCard[] = [
  { label: "Total Keys", value: "48,920", trend: "12.4%", direction: "up", tone: "blue", icon: <KeyIcon /> },
  { label: "Active Keys", value: "31,284", trend: "8.7%", direction: "up", tone: "emerald", icon: <PulseIcon /> },
  { label: "Pending Keys", value: "4,182", trend: "3.1%", direction: "down", tone: "amber", icon: <HourglassIcon /> },
  { label: "Blocked", value: "1,096", trend: "5.8%", direction: "up", tone: "red", icon: <BypassIcon /> },
  { label: "Revenue Today", value: "$2,846", trend: "18.2%", direction: "up", tone: "purple", icon: <RevenueIcon /> },
  { label: "Conversion Rate", value: "64.8%", trend: "2.9%", direction: "up", tone: "emerald", icon: <ConversionIcon /> },
];
const statusSegments = [
  { label: "Active", value: 31284, color: "#34d399", dash: "58 42", offset: "0" },
  { label: "Pending", value: 4182, color: "#fbbf24", dash: "8 92", offset: "-58" },
  { label: "Blocked", value: 1096, color: "#e94560", dash: "2 98", offset: "-66" },
  { label: "Expired", value: 12358, color: "#a78bfa", dash: "23 77", offset: "-68" },
];
const sources = [ { label: "Linkvertise", value: 18320, color: "#38bdf8" }, { label: "Link4m", value: 12680, color: "#34d399" }, { label: "Workink", value: 9240, color: "#a78bfa" } ];
const countries = [ { label: "Vietnam", value: 14280 }, { label: "United States", value: 8160 }, { label: "Indonesia", value: 6320 }, { label: "Brazil", value: 4880 }, { label: "Philippines", value: 3940 } ];
const keyRows: KeyRow[] = [
  { key: "WOLF-8K29-FXQ4", status: "Active", source: "Linkvertise", country: "Vietnam", revenue: "$9.99", hwid: "HW-72F3A1", created: "2026-09-17" },
  { key: "WOLF-3P91-LMZ8", status: "Pending", source: "Link4m", country: "Indonesia", revenue: "$0.00", hwid: "Waiting", created: "2026-09-17" },
  { key: "WOLF-7C55-RDX2", status: "Blocked", source: "Workink", country: "Brazil", revenue: "$0.00", hwid: "Bypass detected", created: "2026-09-16" },
  { key: "WOLF-1N04-QBA7", status: "Expired", source: "Linkvertise", country: "United States", revenue: "$4.99", hwid: "HW-19C8D0", created: "2026-09-12" },
];

export default function Dashboard() {
  return (
    <main className="min-h-screen bg-[#0f0f1e] text-white -m-6 p-6 md:p-8 lg:p-10 bg-[radial-gradient(circle_at_top_left,rgba(233,69,96,.18),transparent_28%),radial-gradient(circle_at_80%_0%,rgba(56,189,248,.12),transparent_24%),linear-gradient(135deg,#0f0f1e,#12122a)]">
      <header className="mb-8 flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between">
        <div><p className="text-sm font-semibold uppercase tracking-[.32em] text-[#e94560]">WolfMod Admin</p><h1 className="mt-2 text-3xl font-black tracking-tight md:text-5xl">License-key analytics</h1><p className="mt-3 max-w-2xl text-sm text-slate-400 md:text-base">Realtime overview for key generation, ad-gate conversion, HWID activation, bypass detection, revenue, and country-level demand.</p></div>
        <div className="rounded-full border border-white/10 bg-white/[.04] px-4 py-2 text-sm text-slate-300 shadow-2xl">Last sync: <span className="text-white">38s ago</span></div>
      </header>
      <section aria-label="KPI summary" className="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-6">{stats.map((stat) => <StatCardView key={stat.label} stat={stat} />)}</section>
      <section aria-label="Analytics charts" className="mt-6 grid grid-cols-1 gap-6 xl:grid-cols-3"><Panel title="Keys activated per day" description="Last 30 days"><LineAreaChart /></Panel><Panel title="Key status breakdown" description="Active, pending, blocked, expired"><DonutChart /></Panel><Panel title="Activations by source" description="Shortlink provider performance"><SourceBars /></Panel></section>
      <section className="mt-6 grid grid-cols-1 gap-6 2xl:grid-cols-[1.6fr_.9fr]"><Panel title="Key lifecycle funnel" description="Drop-off from generated link to HWID activation, with bypass branch highlighted" className="min-h-[420px]"><FunnelDiagram /></Panel><Panel title="Top countries" description="Key-request volume by country field"><CountryBreakdown /></Panel></section>
      <section aria-label="Existing keys data table" className="mt-6 rounded-2xl border border-white/10 bg-white/[.045] p-4 shadow-[0_18px_70px_rgba(0,0,0,.32)] transition hover:border-[#e94560]/30 md:p-6"><div className="mb-5 flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><h2 className="text-xl font-bold">Existing keys</h2><p className="text-sm text-slate-400">Function unchanged. Visual wrapper restyled for WolfMod analytics.</p></div><SkeletonPill label="Live table" /></div>{keyRows.length ? <KeysTable /> : <EmptyState label="No keys created yet" />}</section>
    </main>
  );
}

function StatCardView({ stat }: { stat: StatCard }) { const tone = toneClasses[stat.tone]; return <article className={`group rounded-2xl border ${tone.border} ${tone.glow} bg-white/[.045] p-5 transition duration-300 hover:-translate-y-1 hover:bg-white/[.07]`}><div className={`mb-5 inline-flex h-11 w-11 items-center justify-center rounded-xl ${tone.bg} ${tone.text}`} aria-hidden="true">{stat.icon}</div><p className="text-sm text-slate-400">{stat.label}</p><p className="mt-2 text-3xl font-black tracking-tight">{stat.value}</p><p className={`mt-3 inline-flex items-center gap-1 text-sm ${stat.direction === "up" ? "text-emerald-400" : "text-[#e94560]"}`}><span aria-hidden="true">{stat.direction === "up" ? "↗" : "↘"}</span><span>{stat.trend} vs previous period</span></p></article>; }
function Panel({ title, description, className = "", children }: { title: string; description: string; className?: string; children: React.ReactNode }) { return <section className={`rounded-2xl border border-white/10 bg-white/[.045] p-5 shadow-[0_18px_70px_rgba(0,0,0,.28)] transition duration-300 hover:border-[#e94560]/30 hover:bg-white/[.06] ${className}`}><div className="mb-5"><h2 className="text-lg font-bold">{title}</h2><p className="text-sm text-slate-400">{description}</p></div>{children}</section>; }
function LineAreaChart() { return <svg role="img" aria-label="Line area chart showing keys activated per day for last 30 days" viewBox="0 0 520 240" className="h-64 w-full overflow-visible"><defs><linearGradient id="areaFill" x1="0" x2="0" y1="0" y2="1"><stop stopColor="#e94560" stopOpacity=".45"/><stop offset="1" stopColor="#e94560" stopOpacity="0"/></linearGradient></defs>{[40,90,140,190].map((y)=><line key={y} x1="10" x2="510" y1={y} y2={y} stroke="rgba(255,255,255,.08)" />)}<path d="M18 184 C64 160 76 172 112 132 S176 92 212 112 S280 178 326 92 S402 64 442 84 S486 48 506 38 L506 220 L18 220 Z" fill="url(#areaFill)"/><path d="M18 184 C64 160 76 172 112 132 S176 92 212 112 S280 178 326 92 S402 64 442 84 S486 48 506 38" fill="none" stroke="#e94560" strokeWidth="4" strokeLinecap="round"/>{[18,112,212,326,442,506].map((x,i)=><circle key={x} cx={x} cy={[184,132,112,92,84,38][i]} r="5" fill="#12122a" stroke="#e94560" strokeWidth="3"/>)}</svg>; }
function DonutChart() { const total = statusSegments.reduce((sum, item) => sum + item.value, 0); return <div className="flex flex-col items-center gap-5 md:flex-row"><svg role="img" aria-label="Donut chart: active, pending, blocked, and expired key status breakdown" viewBox="0 0 140 140" className="h-48 w-48 -rotate-90"><circle cx="70" cy="70" r="48" fill="none" stroke="rgba(255,255,255,.08)" strokeWidth="18" />{statusSegments.map((segment)=><circle key={segment.label} cx="70" cy="70" r="48" fill="none" stroke={segment.color} strokeWidth="18" strokeDasharray={segment.dash} strokeDashoffset={segment.offset} pathLength="100" strokeLinecap="round"/>)}<g className="rotate-90 origin-center"><text x="70" y="66" textAnchor="middle" fill="white" fontSize="18" fontWeight="800">{total.toLocaleString()}</text><text x="70" y="84" textAnchor="middle" fill="#94a3b8" fontSize="10">total</text></g></svg><div className="w-full space-y-3">{statusSegments.map((segment)=><div key={segment.label} className="flex items-center justify-between rounded-xl bg-white/[.04] px-3 py-2"><span className="flex items-center gap-2 text-sm text-slate-300"><span className="h-2.5 w-2.5 rounded-full" style={{ backgroundColor: segment.color }} />{segment.label}</span><span className="font-mono text-sm text-white">{segment.value.toLocaleString()}</span></div>)}</div></div>; }
function SourceBars() { const max = Math.max(...sources.map((item) => item.value)); return <div role="img" aria-label="Horizontal bar chart showing activations grouped by Linkvertise, Link4m, and Workink" className="space-y-5">{sources.map((item)=><div key={item.label}><div className="mb-2 flex justify-between text-sm"><span className="text-slate-300">{item.label}</span><span className="font-mono text-white">{item.value.toLocaleString()}</span></div><div className="h-4 rounded-full bg-white/[.07]"><div className="h-4 rounded-full transition-all duration-700" style={{ width: `${(item.value / max) * 100}%`, background: `linear-gradient(90deg, ${item.color}, #e94560)` }} /></div></div>)}</div>; }
function FunnelDiagram() { return <svg role="img" aria-label="Funnel diagram: Link Generated to Ad-Gate Completed to CAPTCHA Verified to HWID Activated, with blocked bypass side path" viewBox="0 0 960 430" className="h-[430px] w-full"><defs><linearGradient id="funnel" x1="0" x2="1"><stop stopColor="#38bdf8"/><stop offset=".55" stopColor="#a78bfa"/><stop offset="1" stopColor="#34d399"/></linearGradient><filter id="glow"><feGaussianBlur stdDeviation="6" result="blur"/><feMerge><feMergeNode in="blur"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs><path d="M60 90 H900 L810 165 H150 Z" fill="url(#funnel)" opacity=".22" stroke="rgba(255,255,255,.18)"/><path d="M150 170 H810 L730 245 H230 Z" fill="url(#funnel)" opacity=".28" stroke="rgba(255,255,255,.18)"/><path d="M230 250 H730 L665 325 H295 Z" fill="url(#funnel)" opacity=".34" stroke="rgba(255,255,255,.18)"/><path d="M295 330 H665 L620 395 H340 Z" fill="url(#funnel)" opacity=".42" stroke="rgba(255,255,255,.18)"/><path d="M810 198 C875 205 884 248 920 278" fill="none" stroke="#e94560" strokeWidth="8" strokeLinecap="round" filter="url(#glow)"/><circle cx="920" cy="278" r="18" fill="#e94560" opacity=".85"/><text x="928" y="272" fill="#fff" fontSize="15" fontWeight="800">Blocked</text><text x="928" y="294" fill="#fecdd3" fontSize="13">1,096 • 2.2%</text>{[[480,126,"Link Generated","48,920","start"],[480,207,"Ad-Gate Completed","39,460","19.3% drop"],[480,288,"CAPTCHA Verified","35,112","11.0% drop"],[480,365,"HWID Activated","31,284","10.9% drop"]].map(([x,y,label,value,drop])=><g key={String(label)}><text x={Number(x)} y={Number(y)-10} textAnchor="middle" fill="white" fontSize="22" fontWeight="800">{label}</text><text x={Number(x)} y={Number(y)+18} textAnchor="middle" fill="#cbd5e1" fontSize="16">{value} • {drop}</text></g>)}</svg>; }
function CountryBreakdown() { const max = Math.max(...countries.map((country) => country.value)); return <ol className="space-y-4" aria-label="Top countries by key request volume">{countries.map((country,index)=><li key={country.label} className="rounded-xl bg-white/[.035] p-3"><div className="mb-2 flex items-center justify-between"><span className="text-sm text-slate-300"><span className="mr-2 font-mono text-[#e94560]">#{index + 1}</span>{country.label}</span><span className="font-mono text-sm">{country.value.toLocaleString()}</span></div><div className="h-3 rounded-full bg-white/[.07]"><div className="h-3 rounded-full bg-gradient-to-r from-[#e94560] to-emerald-400" style={{ width: `${(country.value / max) * 100}%` }} /></div></li>)}</ol>; }
function KeysTable() { const statusClass: Record<KeyRow["status"], string> = { Active: "bg-emerald-400/10 text-emerald-300", Pending: "bg-amber-400/10 text-amber-300", Blocked: "bg-[#e94560]/10 text-[#ff8fa0]", Expired: "bg-purple-400/10 text-purple-300" }; return <div className="overflow-x-auto"><table className="w-full min-w-[760px] border-separate border-spacing-y-2"><thead><tr className="text-left text-xs uppercase tracking-[.2em] text-slate-500"><th className="px-4 py-2">Key</th><th className="px-4 py-2">Status</th><th className="px-4 py-2">Source</th><th className="px-4 py-2">Country</th><th className="px-4 py-2">Revenue</th><th className="px-4 py-2">HWID</th><th className="px-4 py-2">Created</th></tr></thead><tbody>{keyRows.map((row)=><tr key={row.key} className="bg-[#12122a]/80 text-sm transition hover:bg-white/[.07]"><td className="rounded-l-xl px-4 py-4 font-mono text-white">{row.key}</td><td className="px-4 py-4"><span className={`rounded-full px-3 py-1 text-xs font-semibold ${statusClass[row.status]}`}>{row.status}</span></td><td className="px-4 py-4 text-slate-300">{row.source}</td><td className="px-4 py-4 text-slate-300">{row.country}</td><td className="px-4 py-4 font-mono text-slate-200">{row.revenue}</td><td className="px-4 py-4 text-slate-300">{row.hwid}</td><td className="rounded-r-xl px-4 py-4 text-slate-400">{row.created}</td></tr>)}</tbody></table></div>; }
function EmptyState({ label }: { label: string }) { return <div className="flex min-h-48 flex-col items-center justify-center rounded-2xl border border-dashed border-white/10 text-center"><svg aria-hidden="true" viewBox="0 0 120 80" className="mb-3 h-20 w-28 text-[#e94560]"><path d="M12 62 C30 18 50 18 64 44 S92 72 108 24" fill="none" stroke="currentColor" strokeWidth="6" strokeLinecap="round"/><circle cx="64" cy="44" r="8" fill="currentColor" opacity=".35"/></svg><p className="text-sm text-slate-400">{label}</p></div>; }
function SkeletonPill({ label }: { label: string }) { return <span className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/[.04] px-3 py-1 text-xs text-slate-300"><span className="h-2 w-2 animate-pulse rounded-full bg-emerald-400" />{label}</span>; }
function KeyIcon() { return <svg viewBox="0 0 24 24" className="h-6 w-6" fill="none" stroke="currentColor" strokeWidth="1.8"><path d="M8.5 14.5a5 5 0 1 1 3.8-3.2L22 21h-4v-3h-3v-3h-3l-1.2-1.2a5 5 0 0 1-2.3.7Z"/><circle cx="6.5" cy="9.5" r="1.5" fill="currentColor"/></svg>; }
function PulseIcon() { return <svg viewBox="0 0 24 24" className="h-6 w-6" fill="none" stroke="currentColor" strokeWidth="1.8"><path d="M3 12h4l2-6 4 12 2-6h6"/><circle cx="18" cy="12" r="3" opacity=".25" fill="currentColor"/></svg>; }
function HourglassIcon() { return <svg viewBox="0 0 24 24" className="h-6 w-6" fill="none" stroke="currentColor" strokeWidth="1.8"><path d="M6 3h12M6 21h12M8 3c0 5 8 5 8 9s-8 4-8 9M16 3c0 5-8 5-8 9s8 4 8 9"/><path d="M9 18h6" opacity=".45"/></svg>; }
function BypassIcon() { return <svg viewBox="0 0 24 24" className="h-6 w-6" fill="none" stroke="currentColor" strokeWidth="1.8"><path d="M12 3 4 6v6c0 5 3.4 8 8 9 4.6-1 8-4 8-9V6l-8-3Z"/><path d="m8 8 8 8M16 8l-8 8"/></svg>; }
function RevenueIcon() { return <svg viewBox="0 0 24 24" className="h-6 w-6" fill="none" stroke="currentColor" strokeWidth="1.8"><path d="M4 18V7a2 2 0 0 1 2-2h12v14H6a2 2 0 0 1-2-2Z"/><path d="M8 9h7M8 13h5M17 5v14"/><circle cx="18" cy="17" r="3" fill="currentColor" opacity=".25"/></svg>; }
function ConversionIcon() { return <svg viewBox="0 0 24 24" className="h-6 w-6" fill="none" stroke="currentColor" strokeWidth="1.8"><path d="M4 17 10 11l4 4 6-8"/><path d="M15 7h5v5"/><circle cx="7" cy="17" r="3" fill="currentColor" opacity=".22"/></svg>; }
